title: ReconMMS Documentation
description: Documentation for the Recon Matter Management System
remote_theme: just-the-docs/just-the-docs@v0.7.0

url: https://staggerlee9.github.io
baseurl: /RA-docs

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Mermaid configuration
mermaid:
  enabled: true
  version: "10.6.1"
  parameters:
    theme: forest

# Collections configuration
collections:
  pages:
    output: true
    permalink: "/:path/"

# Just the Docs specific configuration
aux_links:
  "View on GitHub": "https://github.com/StaggerLee9/RA-docs"

search_enabled: true
color_scheme: light
back_to_top: true
back_to_top_text: "Back to top"
footer_content: "Copyright &copy; 2024"

# Enable copy code button
enable_copy_code_button: true

# Enable anchor headings
heading_anchors: true

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Search settings
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Maximum amount of items in search results
search_max_preview_chars: 150

# Default layout configuration
defaults:
  -
    scope:
      path: ""
    values:
      layout: default