source "https://rubygems.org"

# GitHub Pages gem (includes Jekyll and other dependencies)
gem "github-pages", group: :jekyll_plugins

# Jekyll plugins supported by GitHub Pages
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-remote-theme"
end

# Required for Ruby 3+
gem "webrick"